name: digital_wellbeing_app
description: A Flutter app for digital wellbeing and usage monitoring.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Core dependencies
  cupertino_icons: ^1.0.2
  
  # HTTP requests (uncomment when you want to add API calls)
  # http: ^1.1.0
  
  # For app usage statistics (add later for real implementation)
  usage_stats: ^1.3.0 # Uncommented to enable usage statistics
  
  # For managing device apps (add later for real implementation)
  # device_apps: ^2.2.0
  
  # For local notifications (add later for real implementation)
  # flutter_local_notifications: ^16.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/
  
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic